// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SetMultipleStartupProjects
{
    internal sealed partial class Vsix
    {
        public const string Id = "SetMultipleStartupProjects.e623d6ff-72b0-46d9-b126-235dea7a4be7";
        public const string Name = "Multiple Startup Projects";
        public const string Description = @"Set multiple startup projects directly from solution explorer. Select mutliple projcets, right-click and then set as startup projects.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Niklas Hempel";
        public const string Tags = "projects, startup";
    }
}
