// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SetMultipleStartupProjects
{
    internal sealed partial class Vsix
    {
        public const string Id = "SetMultipleStartupProjects.e623d6ff-72b0-46d9-b126-235dea7a4be7";
        public const string Name = "SetMultipleStartupProjects";
        public const string Description = @"Fast way to set multiple startup projects.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Niklas Hempel";
        public const string Tags = "";
    }
}
